### ISSUE TITLE
Block: Improve styling for blocks with `alignnone`

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12972]
## Feature Description

When using the embed block or shortcode without any alignment, we don't currently enforce a max width. Depending on the theme this this causes the story player to have very large dimensions.

Something like this should work:

```css
.web-stories-embed.alignnone .wp-block-embed__wrapper {
  max-width: var(--width);
}
```
