### ISSUE TITLE
WordPress 5.9 Fixes

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9733]
## Task Description

Let's update our local environments to WP 5.9 Beta once it comes out, so we can do some manual testing ahead of the RC.

**Comment by swissspidy** [comment]
One tiny issue I noticed with the embed block in the Twenty Twenty-Two theme:

The story poster placeholder is too big and thus cut off:
![Screenshot 2021-11-17 at 16 48 31](https://user-images.githubusercontent.com/841956/142233985-445cf41c-5e6d-4437-9aea-c4dd599b8fb5.png)

This is easily fixable with the following CSS though:

```css
.web-stories-list__story-poster-placeholder {
    box-sizing: border-box;
}
```
